# ==========================================
# VARIÁVEIS GLOBAIS
# ==========================================
@baseUrl = http://localhost:3333
# Cole o token gerado no login aqui embaixo, logo após o sinal de igual:
@token = ""

# ==========================================
# 2. MANGÁS
# ==========================================

### Listar Todos os Mangás (Público)
GET {{baseUrl}}/mangas

### Criar Mangá (Requer @token de Admin)
POST {{baseUrl}}/mangas
Content-Type: application/json

{
  "title": "Solo Leveling",
  "author": "Chugong",
  "genres": "Ação, Fantasia, Shonen",
  "synopsis": "Dez anos atrás, O Portão conectou o mundo real com o reino da magia e monstros...",
  "coverUrl": "https://m.media-amazon.com/images/I/816hywlmu-L._SL1500_.jpg",
  "status": "andamento",
  "releaseYear": 2018,
  "publisher": "D&C Media"
}

### Cadastrar um novo Usuário (POST)
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Leitor Assíduo",
  "email": "leitor@overreader.com"
}

### Listar todos os usuários (GET)
GET http://localhost:3333/users

###

### Banir ou suspender um usuário (PATCH)
# Mude o "1" pelo ID do usuário que você criou na etapa anterior
PATCH http://localhost:3333/users/1/status
Content-Type: application/json

{
  "status": "ATIVO"
}


### Avaliar um Mangá (1 a 5 estrelas)
# IMPORTANTE: Use o userId de um usuário que você já criou, e o mangaId de um mangá que você já cadastrou!
POST http://localhost:3333/reviews
Content-Type: application/json

{
  "userId": 1,
  "mangaId": 1,
  "rating": 5,
}

### Favoritar um Mangá
POST http://localhost:3333/favorites
Content-Type: application/json

{
  "userId": 1,
  "mangaId": 1
}

###

### Comentar em um Mangá
POST http://localhost:3333/comments
Content-Type: application/json

{
  "userId": 1,
  "mangaId": 1,
  "content": "Arte simplesmente incrível! Ansioso pelo próximo capítulo."
}

### Listar Mangás
GET http://localhost:3333/mangas

### Atualizar Mangá (Ex: mudar o status)
PUT http://localhost:3333/mangas/1
Content-Type: application/json

{
  "status": "Em andamento"
}

### Deletar Mangá
DELETE http://localhost:3333/mangas/1
